// =============================================================================
// Native OS window with embedded WebView for the NeuronPrompter frontend.
//
// Uses tao for window management (Win32/Cocoa/GTK) and wry for WebView
// embedding (WebView2 on Windows, WebKit on macOS/Linux). Provides a splash
// screen during server startup, then transitions to the main application
// window once the server is ready.
//
// Threading constraint: tao's event loop must run on the main thread
// (platform requirement on macOS and Windows). The axum HTTP server runs
// in a background thread with its own tokio runtime.
//
// This module is conditionally compiled behind the `gui` feature flag.
// =============================================================================

#![allow(unsafe_code)]

use std::rc::Rc;

use tao::dpi::LogicalSize;
use tao::event::{Event, WindowEvent};
use tao::event_loop::{ControlFlow, EventLoopBuilder, EventLoopProxy};
use tao::platform::run_return::EventLoopExtRunReturn;
use tao::window::{Icon, WindowBuilder};
use wry::WebViewBuilder;

/// Embedded 256x256 RGBA PNG of the NeuronPrompter "P" icon with the brand's
/// purple-to-cyan gradient. Pre-generated by tools/gen/generate_icon.py.
/// Decoded at runtime to raw RGBA pixels for tao's Icon::from_rgba().
/// Used on macOS and Linux where there is no embedded resource mechanism.
#[cfg(not(target_os = "windows"))]
const ICON_PNG: &[u8] = include_bytes!("../assets/icon_256.png");

/// Decodes the embedded icon PNG and creates a tao Icon from the raw RGBA
/// pixel data. Returns None if decoding fails. Used on macOS and Linux for
/// the window/dock icon. On Windows, the icon is loaded from the exe's
/// resource section instead (see `apply_resource_icon`).
#[cfg(not(target_os = "windows"))]
fn load_window_icon() -> Option<Icon> {
    let img = image::load_from_memory(ICON_PNG).ok()?.into_rgba8();
    let (w, h) = img.dimensions();
    Icon::from_rgba(img.into_raw(), w, h).ok()
}

/// On Windows, returns None because the icon is set after window creation
/// via `apply_resource_icon`, which loads the multi-resolution ICO from
/// the exe's resource section (embedded by winres at link time).
#[cfg(target_os = "windows")]
fn load_window_icon() -> Option<Icon> {
    None
}

/// Loads the multi-resolution ICO from the Windows executable's resource
/// section and sets it on the given window via Win32 `WM_SETICON` messages
/// for both the small icon (taskbar) and the big icon (Alt+Tab).
#[cfg(target_os = "windows")]
fn apply_resource_icon(window: &tao::window::Window) {
    use tao::platform::windows::WindowExtWindows;
    use windows::Win32::Foundation::{HWND, LPARAM, WPARAM};
    use windows::Win32::System::LibraryLoader::GetModuleHandleW;
    use windows::Win32::UI::WindowsAndMessaging::{
        GetSystemMetrics, IMAGE_ICON, LR_DEFAULTCOLOR, LoadImageW, SM_CXICON, SM_CXSMICON,
        SM_CYICON, SM_CYSMICON, SendMessageW, WM_SETICON,
    };
    use windows::core::PCWSTR;

    const ICON_SMALL: usize = 0;
    const ICON_BIG: usize = 1;

    // Resource ID 1 -- equivalent to MAKEINTRESOURCE(1).
    // The Win32 API encodes integer resource IDs as pointer values;
    // this is not a dangling pointer dereference.
    #[allow(clippy::manual_dangling_ptr)]
    let resource_id = PCWSTR(1 as *const u16);

    unsafe {
        let Ok(hinstance) = GetModuleHandleW(None) else {
            return;
        };

        let hwnd = HWND(window.hwnd() as *mut _);

        // Small icon for taskbar
        let small_width = GetSystemMetrics(SM_CXSMICON);
        let small_height = GetSystemMetrics(SM_CYSMICON);
        if let Ok(h) = LoadImageW(
            Some(hinstance.into()),
            resource_id,
            IMAGE_ICON,
            small_width,
            small_height,
            LR_DEFAULTCOLOR,
        ) {
            SendMessageW(
                hwnd,
                WM_SETICON,
                Some(WPARAM(ICON_SMALL)),
                Some(LPARAM(h.0 as isize)),
            );
        }

        // Big icon for Alt+Tab
        let large_width = GetSystemMetrics(SM_CXICON);
        let large_height = GetSystemMetrics(SM_CYICON);
        if let Ok(h) = LoadImageW(
            Some(hinstance.into()),
            resource_id,
            IMAGE_ICON,
            large_width,
            large_height,
            LR_DEFAULTCOLOR,
        ) {
            SendMessageW(
                hwnd,
                WM_SETICON,
                Some(WPARAM(ICON_BIG)),
                Some(LPARAM(h.0 as isize)),
            );
        }
    }
}

/// Background color matching `--bg-base: #0a0f1a` (fully opaque).
const MAIN_WINDOW_BG: (u8, u8, u8, u8) = (10, 15, 26, 255);

/// Custom user events for coordinating splash lifecycle, server readiness,
/// and window close actions on the tao event loop.
enum UserEvent {
    /// The server has bound its TCP port and is ready. Carries the URL.
    ServerReady(String),
    /// The server thread terminated during startup without providing a URL.
    ServerFailed,
    /// Frontend requested window close via IPC.
    CloseRequested,
}

// ---------------------------------------------------------------------------
// Linux Wayland compatibility
// ---------------------------------------------------------------------------

#[cfg(target_os = "linux")]
fn ensure_x11_backend() {
    if std::env::var_os("WAYLAND_DISPLAY").is_some() && std::env::var_os("GDK_BACKEND").is_none() {
        tracing::info!(
            "Wayland session detected; setting GDK_BACKEND=x11 for WebView compatibility"
        );
        // SAFETY: Called before any GTK or event-loop initialisation.
        unsafe {
            std::env::set_var("GDK_BACKEND", "x11");
        }
    }
}

#[cfg(not(target_os = "linux"))]
fn ensure_x11_backend() {}

// ---------------------------------------------------------------------------
// Pre-flight GUI availability check
// ---------------------------------------------------------------------------

/// Checks whether the native GUI can be created on the current platform.
///
/// # Errors
///
/// Returns a human-readable error string describing what is missing.
pub fn preflight_gui_check() -> Result<(), String> {
    #[cfg(target_os = "linux")]
    {
        let lib = std::ffi::CString::new("libwebkit2gtk-4.1.so.0")
            .map_err(|e| format!("CString error: {e}"))?;
        let handle = unsafe { libc::dlopen(lib.as_ptr(), libc::RTLD_LAZY) };
        if handle.is_null() {
            return Err(
                "WebKitGTK runtime library not found (libwebkit2gtk-4.1.so.0).\n\
                 Install with: sudo apt install libwebkit2gtk-4.1-0\n\
                 Or use headless mode: neuronprompter serve"
                    .into(),
            );
        }
        unsafe {
            libc::dlclose(handle);
        }
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// GUI launch with splash screen
// ---------------------------------------------------------------------------

/// Launches the native GUI with a transparent splash screen shown during
/// server startup, transitioning to the main application window once the
/// server is ready.
///
/// **Lifecycle:**
///
/// 1. A compact (480x180), frameless, transparent splash window appears
///    centered on the primary monitor. A pre-rendered PNG with the
///    "NeuronPrompter" logo is rendered using platform-native APIs.
/// 2. A bridge thread blocks on `url_rx` waiting for the server thread to
///    send its bound URL. When received, it forwards the URL as a
///    `UserEvent::ServerReady` to the tao event loop.
/// 3. On `ServerReady`: the splash window is destroyed, and the full-size
///    main application window (1280x800, frameless, with WebView) is created.
/// 4. On `ServerFailed`: the splash is destroyed and the event loop exits.
/// 5. On window close: `shutdown_tx` fires to signal the server, and the
///    event loop exits.
///
/// This function blocks the calling thread until the user closes the main
/// window. It must be called from the main thread.
///
/// # Errors
///
/// Returns an error if the event loop, splash window, or bridge thread
/// cannot be created.
#[allow(unused_assignments, clippy::too_many_lines)]
pub fn run_gui_with_splash(
    url_rx: std::sync::mpsc::Receiver<String>,
    shutdown_tx: tokio::sync::oneshot::Sender<()>,
) -> Result<(), Box<dyn std::error::Error>> {
    ensure_x11_backend();

    let mut event_loop = EventLoopBuilder::<UserEvent>::with_user_event().build();
    let proxy: EventLoopProxy<UserEvent> = event_loop.create_proxy();

    // Load window icon (macOS/Linux from embedded PNG, Windows from exe resources)
    let window_icon = load_window_icon();

    // --- Create splash window ---
    #[cfg(not(target_os = "linux"))]
    let splash_builder = WindowBuilder::new()
        .with_title("NeuronPrompter")
        .with_decorations(false)
        .with_resizable(false)
        .with_always_on_top(true)
        .with_transparent(true)
        .with_window_icon(window_icon.clone())
        .with_inner_size(LogicalSize::new(480.0, 180.0));

    #[cfg(target_os = "linux")]
    let splash_builder = {
        use tao::platform::unix::WindowBuilderExtUnix;
        WindowBuilder::new()
            .with_title("NeuronPrompter")
            .with_decorations(false)
            .with_resizable(false)
            .with_always_on_top(true)
            .with_transparent(true)
            .with_window_icon(window_icon.clone())
            .with_inner_size(LogicalSize::new(480.0, 180.0))
            .with_transparent_draw(false)
    };

    let splash_window = Rc::new(splash_builder.build(&event_loop)?);

    #[cfg(target_os = "windows")]
    apply_resource_icon(&splash_window);

    // Center the splash window on the primary monitor
    #[allow(clippy::cast_possible_wrap)]
    if let Some(monitor) = splash_window.current_monitor() {
        let monitor_pos = monitor.position();
        let monitor_size = monitor.size();
        let window_size = splash_window.outer_size();
        let x = monitor_pos.x + (monitor_size.width as i32 - window_size.width as i32) / 2;
        let y = monitor_pos.y + (monitor_size.height as i32 - window_size.height as i32) / 2;
        splash_window.set_outer_position(tao::dpi::PhysicalPosition::new(x, y));
    }

    // Render the transparent PNG onto the splash window
    if let Err(e) = crate::splash::render_splash_on_window(&splash_window) {
        tracing::warn!("transparent splash rendering failed, using fallback: {e}");
    }

    // --- Bridge thread ---
    let bridge_proxy = event_loop.create_proxy();
    std::thread::Builder::new()
        .name("splash-bridge".into())
        .spawn(move || match url_rx.recv() {
            Ok(url) => {
                let _ = bridge_proxy.send_event(UserEvent::ServerReady(url));
            }
            Err(_) => {
                let _ = bridge_proxy.send_event(UserEvent::ServerFailed);
            }
        })?;

    // --- Event loop state ---
    let mut splash: Option<Rc<tao::window::Window>> = Some(splash_window);
    let mut main_state: Option<(wry::WebView, Rc<tao::window::Window>)> = None;
    let mut shutdown_tx = Some(shutdown_tx);

    let _exit_code = event_loop.run_return(move |event, event_loop_target, control_flow| {
        *control_flow = ControlFlow::Wait;

        match event {
            // --- Phase transition: server is ready, swap splash for main window ---
            Event::UserEvent(UserEvent::ServerReady(url)) => {
                // Destroy the splash window
                splash.take();

                #[cfg(target_os = "windows")]
                unsafe {
                    std::env::set_var("WEBVIEW2_DEFAULT_BACKGROUND_COLOR", "FF0A0F1A");
                }

                // Create the main application window
                let window = match WindowBuilder::new()
                    .with_title("NeuronPrompter")
                    .with_decorations(false)
                    .with_window_icon(window_icon.clone())
                    .with_inner_size(LogicalSize::new(1280.0, 800.0))
                    .with_min_inner_size(LogicalSize::new(900.0, 600.0))
                    .build(event_loop_target)
                {
                    Ok(w) => Rc::new(w),
                    Err(e) => {
                        tracing::error!("failed to create main window: {e}");
                        if let Some(tx) = shutdown_tx.take() {
                            let _ = tx.send(());
                        }
                        *control_flow = ControlFlow::Exit;
                        return;
                    }
                };

                #[cfg(target_os = "windows")]
                apply_resource_icon(&window);

                let ipc_window = Rc::clone(&window);
                let ipc_proxy = proxy.clone();
                let allowed_origin = url.clone();

                let webview = match WebViewBuilder::new()
                    .with_url(&url)
                    .with_background_color(MAIN_WINDOW_BG)
                    .with_devtools(cfg!(debug_assertions))
                    .with_navigation_handler(move |nav_url: String| {
                        // F21: Compare parsed origins (scheme+host+port) instead
                        // of a raw string prefix to prevent bypass via crafted URLs.
                        match (url::Url::parse(&nav_url), url::Url::parse(&allowed_origin)) {
                            (Ok(nav), Ok(allowed)) => {
                                nav.scheme() == allowed.scheme()
                                    && nav.host() == allowed.host()
                                    && nav.port_or_known_default()
                                        == allowed.port_or_known_default()
                            }
                            _ => false,
                        }
                    })
                    .with_ipc_handler(move |request: wry::http::Request<String>| {
                        match request.body().as_str() {
                            "minimize" => ipc_window.set_minimized(true),
                            "maximize" => {
                                let is_maximized = ipc_window.is_maximized();
                                ipc_window.set_maximized(!is_maximized);
                            }
                            "close" => {
                                let _ = ipc_proxy.send_event(UserEvent::CloseRequested);
                            }
                            "drag" => {
                                let _ = ipc_window.drag_window();
                            }
                            cmd if cmd.starts_with("open_url:") => {
                                let ext_url = cmd.trim_start_matches("open_url:");
                                if ext_url.starts_with("https://") || ext_url.starts_with("http://")
                                {
                                    let _ = opener::open(ext_url);
                                }
                            }
                            _ => {}
                        }
                    })
                    .build(&window)
                {
                    Ok(wv) => wv,
                    Err(e) => {
                        tracing::error!("failed to create WebView: {e}");
                        if let Some(tx) = shutdown_tx.take() {
                            let _ = tx.send(());
                        }
                        *control_flow = ControlFlow::Exit;
                        return;
                    }
                };

                main_state = Some((webview, window));
            }

            // Server startup failure.
            Event::UserEvent(UserEvent::ServerFailed) => {
                splash.take();
                tracing::error!("server failed during startup");
                *control_flow = ControlFlow::Exit;
            }

            // Window close: native or IPC.
            Event::WindowEvent {
                event: WindowEvent::CloseRequested,
                ..
            }
            | Event::UserEvent(UserEvent::CloseRequested) => {
                // Drop WebView before Window (required on macOS).
                main_state.take();
                splash.take();

                if let Some(tx) = shutdown_tx.take() {
                    let _ = tx.send(());
                }
                *control_flow = ControlFlow::Exit;
            }

            _ => {}
        }
    });

    Ok(())
}
